#!/usr/bin/env python3
# Updates the user page on the gemsite with the current user list

import cgi
import pwd
import os.path
import sys

users = 0

sys.stdout.write("20 text/gemini\r\n")
sys.stdout.write('# USERS\n\n')
for user in sorted(pwd.getpwall(), key=lambda x: x.pw_name):
    # if the user doesn't have a public_gemini folder, skip
    if not os.path.exists(os.path.join(user.pw_dir, 'public_gemini')) or user.pw_gid != 100:
        continue

    # if .hidden exists in the public_html, skip it
    if os.path.exists(os.path.join(user.pw_dir, 'public_gemini', '.hidden')):
        continue

    gecos = ''
    if user.pw_gecos:
        gecos = ' - %s' % user.pw_gecos
    entry = "=> /~%s %s%s\n" % (user.pw_name, user.pw_name, gecos)
    users += 1
    sys.stdout.write(entry)

sys.stdout.write("\n\nTotal Users: %d\n" % users)
sys.stdout.write("\nUsers can be excluded from this list by creating a '.hidden' file in their public_gemini.")
sys.stdout.write("\r\n")